
name: prod-build-and-deploy

on:
  push:
    branches:
      - dev
jobs:
  # To build the project
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: yarn install
      - name: Building project
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build s3://webquest-demo
      - name: Validate cache of cloudfront
        run: aws cloudfront create-invalidation --distribution-id EMQY8AGBBMRCU --path '/*'
